name: feature workflow
on:
  push:
  workflow_dispatch:
    
    # branches-ignore:
    #   - 'main'
jobs:
  feature-workflow:
    if: github.ref_name != 'main'
    uses: daws-90s/workflows/.github/workflows/nodejs-eks-feature.yaml@main
    with:
      project: roboshop
      component: catalogue

  main-workflow:
    runs-on:  ubuntu-latest
    steps:
      - name: main workflow
        run: echo "this runs when a commit comes to main branch"